### ISSUE TITLE
Documentar como executar o bot

### ISSUE THREAD

**Issue by rodrigondec** [jerimumhs/JerimumBot#20]
Atualmente nosso readme não tem o conteúdo `configuração para desenvolvimento`. 
Deve ser criado esse conteúdo

- [x] Documentar como instalar dependências de desenenvolvimento (>python3.6, python3-dev, python3-venv, GCC)
- [x] Documentar como criar um env em python usando a documentação https://docs.python.org/3/library/venv.html
- [x] Documentar como ativar o env criado
- [x] Documentar como instalar as dependências do `requirents.txt`
- [x] Documentar como criar o arquivo `.env` baseado no `.env.example`
- [x] Documentar como ativar o `.env` no bash
- [x] Documentar como criar um bot teste  usando o `Bot Father` https://telegram.me/BotFather 
- [x] Documentar como pegar o token do bot para executar o código

Exemplos de repositórios documentados
- https://github.com/rodrigondec/rctech
- https://github.com/rodrigondec/Open_CliEng

Gostei desse exemplo de markdown
- https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab

**Comment by dantasl** [comment]
Trabalhando nessa issue.
