### ISSUE TITLE
Ações do bot só para admin

### ISSUE THREAD

**Issue by claranobre** [jerimumhs/JerimumBot#29]
A ação de casa aberta e casa fechada precisam ser usadas só pelos administradores do grupo.

**Comment by dantasl** [comment]
Trabalhando nessa issue.

**Comment by rodrigondec** [comment]
Tem o módulo de auth https://github.com/jerimumhs/JerimumBot/blob/master/core/auth.py

Usando isso com if na sua função da pra fazer esse controle

**Comment by rodrigondec** [comment]
@vertumno ainda está fazendo essa issue?
