### ISSUE TITLE
Anti Spam

### ISSUE THREAD

**Issue by fguisso** [jerimumhs/JerimumBot#40]
Criar uma função global que evite o bot a soltar spam, por exemplo:

Chamando o comando /coach ele traz uma frase, se você chamar novamente já tem um timeout que faz o bot responder com uma mensagem de timeout, mas esta mensagem pode ser um spam, então tem que ter algo que permita uma unica mensagem de timeout e depois silencie a função do bot até o timeout terminar.

A ideia de ser global é poder usar isso em qualquer função que sejá necessario o anti spam.

**Comment by rodrigondec** [comment]
Criei um wrapper para isso, mas podemos utilizar a lib https://github.com/tomasbasham/ratelimit
