### ISSUE TITLE
Notificação casa aberta/fechada

### ISSUE THREAD

**Issue by rodrigondec** [jerimumhs/JerimumBot#5]
seria legal poder avisar pelo bot que a casa foi fechada ou aberta. 

Com o intuito de poder automatizar com algum sensor ou fechadura eletrônica posteriormente

Utilizar o https://t.me/@getidsbot para pegar os ID's dos stickers da casa aberta e casa fechada

- [ ] comando de casa aberta
- [ ] comando de casa fechada

**Comment by dantasl** [comment]
Trabalhando nessa issue.
